
export const PAGE = {
    WIDTH : 210,
    HEIGHT : 297,
    PADDING : {
        VERTICAL : 10,
        HORIZONTAL : 10
    },
    INTERVAL : 10,
    TITLE_LINES_COUNT : 2,
    LINES_COUNT : 5,
    NUMBER : {
        HEIGHT : 5,
        WIDTH : 5
    }
};

export const LINE = {
    PADDING : {
        TOP : 5,
        BOTTOM : 5
    },
    HEIGHT : (PAGE.HEIGHT - PAGE.PADDING.VERTICAL * 2) / PAGE.LINES_COUNT,
    WIDTH : PAGE.WIDTH - 2 * PAGE.PADDING.HORIZONTAL,
    STRING_INTERVAL : 4
};

export const NOTE = {
    HEIGHT : LINE.STRING_INTERVAL,
    WIDTH : 3,
};

export const CHORD = {
    HORIZONTAL_INTERVAL : NOTE.WIDTH * 2
}

export const TACT = {
    DURATION_WIDTH : CHORD.HORIZONTAL_INTERVAL,
    Y : LINE.PADDING.TOP + NOTE.HEIGHT / 2
}

export const HEADER = {
    WIDTH : LINE.WIDTH,
    HEIGHT : PAGE.HEIGHT - 2 * PAGE.PADDING.VERTICAL - PAGE.TITLE_LINES_COUNT * LINE.HEIGHT,
    X : PAGE.PADDING.HORIZONTAL,
    Y : PAGE.PADDING.VERTICAL
}

export const STRING = {
    WIDTH : NOTE.HEIGHT / 10
}
